version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "build react app"
          command: |
            npm run build

      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .next

  deploy:
    docker:
      - image: circleci/node:12

    machine:
      enabled: true

    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "e8:fd:62:98:ce:ed:7e:af:c0:23:38:ba:b0:e8:78:55"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r -o StrictHostKeyChecking=no ~/repo/build/* $SSH_USER@$SSH_TARGET

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master
